
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='bioprocs',
    version='0.1.2',
    description='A set of PyPPL processes for bioinformatics.',
    python_requires='==3.*,>=3.6.0',
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    entry_points={"console_scripts": ["bioprocs = bioprocs.console:main"]},
    packages=['bioprocs', 'bioprocs.console', 'bioprocs.console.pipeline', 'bioprocs.scripts', 'bioprocs.sets', 'bioprocs.utils'],
    package_dir={"": "."},
    package_data={"bioprocs": ["*.toml", "reports/bcftools/*.md", "reports/gsea/*.md", "reports/imtherapy/*.md", "reports/mlearn/*.md", "reports/plot/*.md", "reports/rnaseq/*.md", "reports/stats/*.md", "reports/tcgamaf/*.md", "reports/tumhet/*.md"], "bioprocs.scripts": ["algorithm/*.r", "cluster/*.r", "eqtl/*.r", "genomeplot/*.r", "gsea/*.r", "marray/*.r", "misc/*.r", "mlearn/*.R", "mlearn/*.r", "plink/*.r", "plot/*.R", "plot/*.r", "power/*.r", "rank/*.r", "rnaseq/*.R", "rnaseq/*.r", "sambam/*.r", "stats/*.R", "stats/*.r", "tcga/*.r", "tcgamaf/*.R", "tcgamaf/*.bash", "tcgamaf/*.r", "tfbs/*.r", "tsv/*.R", "tsv/*.r", "tumhet/*.R"], "bioprocs.utils": ["*.bash", "*.r", "*.toml"]},
    install_requires=['completions', 'diot', 'pyparam', 'pyppl==3.*', 'pyppl-annotate', 'pyppl-export', 'pyppl-report', 'toml==0.*'],
)
