
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='biopipen',
    version='0.0.1',
    description='A set of PyPPL processes for bioinformatics.',
    python_requires='==3.*,>=3.6.0',
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    entry_points={"console_scripts": ["biopipen = biopipen.cli:main"]},
    packages=['biopipen', 'biopipen.basics', 'biopipen.cli', 'biopipen.modules'],
    package_dir={"": "."},
    package_data={},
    install_requires=['diot', 'modkit', 'pipen', 'pipen-annotate', 'pyparam', 'rich==9.*', 'toml==0.*'],
)
