
[plugin_opts]
report_no_collapse_pgs=true

[CellRangerMultiPipeline]
input=[
    "example-data/sample1_multi_config.csv",
    "example-data/sample2_multi_config.csv",
]
ids = ["Sample1", "Sample2"]

[CellRangerMulti.envs]
# ncores = 8
# cellranger = "cellranger"
